package com.jiaming.mapper;

import java.util.List;

import com.jiaming.entity.Fruit;
import com.jiaming.entity.User;
import com.jiaming.povos.PricePovo;

public interface FruitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruit
     *
     * @mbggenerated Mon Dec 02 16:01:14 CST 2019
     */
    int deleteByPrimaryKey(Integer fId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruit
     *
     * @mbggenerated Mon Dec 02 16:01:14 CST 2019
     */
    int insert(Fruit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruit
     *
     * @mbggenerated Mon Dec 02 16:01:14 CST 2019
     */
    Fruit selectByPrimaryKey(Integer fId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruit
     *
     * @mbggenerated Mon Dec 02 16:01:14 CST 2019
     */
    List<Fruit> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fruit
     *
     * @mbggenerated Mon Dec 02 16:01:14 CST 2019
     */
    int updateByPrimaryKey(Fruit record);
    
    List<Fruit> selectHotFruits();

	List<Fruit> selectFruisBySwitch(Fruit fruit);
	
	List<Fruit> selectFruitsByPrise(PricePovo pricePovo);

	List<Fruit> findAllFruit();

	Fruit findByFid(int fid);

	void updateFruit(Fruit fruit);

	void deleteFid(int parseInt);

	void addFruit(Fruit fruit);
	
}