package com.jiaming.mapper;

import java.util.List;

import com.jiaming.entity.User;

public interface UserMapper {
	
	List<User> selectUserByEmailOrTel(User user);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Mon Dec 02 16:01:14 CST 2019
     */
    int deleteByPrimaryKey(String uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Mon Dec 02 16:01:14 CST 2019
     */
    boolean insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Mon Dec 02 16:01:14 CST 2019
     */
    User selectByPrimaryKey(String uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Mon Dec 02 16:01:14 CST 2019
     */
    List<User> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Mon Dec 02 16:01:14 CST 2019
     */
    int updateByPrimaryKey(User record);

	User selectUserBySwitch(User user);

	List<User> findAll();

	void add(User user);

	User findByUid(String uid);

	void update(User user);

	void delete(String uid);

}