package com.jiaming.entity;

import java.math.BigDecimal;

public class Fruit {
	
	
	
	
	private Boolean fFlag;
	
	
	
    public Boolean getfFlag() {
		return fFlag;
	}

	public void setfFlag(Boolean fFlag) {
		this.fFlag = fFlag;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fruit.f_id
     *
     * @mbggenerated Mon Dec 02 16:01:14 CST 2019
     */
    private Integer fId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fruit.f_name
     *
     * @mbggenerated Mon Dec 02 16:01:14 CST 2019
     */
    private String fName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fruit.f_norm
     *
     * @mbggenerated Mon Dec 02 16:01:14 CST 2019
     */
    private String fNorm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fruit.f_price
     *
     * @mbggenerated Mon Dec 02 16:01:14 CST 2019
     */
    private BigDecimal fPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fruit.f_summary
     *
     * @mbggenerated Mon Dec 02 16:01:14 CST 2019
     */
    private String fSummary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fruit.f_prompt
     *
     * @mbggenerated Mon Dec 02 16:01:14 CST 2019
     */
    private String fPrompt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fruit.f_hot
     *
     * @mbggenerated Mon Dec 02 16:01:14 CST 2019
     */
    private Boolean fHot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fruit.f_imgcount
     *
     * @mbggenerated Mon Dec 02 16:01:14 CST 2019
     */
    private Integer fImgcount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fruit.c_id
     *
     * @mbggenerated Mon Dec 02 16:01:14 CST 2019
     */
    private String cId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fruit.f_id
     *
     * @return the value of fruit.f_id
     *
     * @mbggenerated Mon Dec 02 16:01:14 CST 2019
     */
    public Integer getfId() {
        return fId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fruit.f_id
     *
     * @param fId the value for fruit.f_id
     *
     * @mbggenerated Mon Dec 02 16:01:14 CST 2019
     */
    public void setfId(Integer fId) {
        this.fId = fId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fruit.f_name
     *
     * @return the value of fruit.f_name
     *
     * @mbggenerated Mon Dec 02 16:01:14 CST 2019
     */
    public String getfName() {
        return fName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fruit.f_name
     *
     * @param fName the value for fruit.f_name
     *
     * @mbggenerated Mon Dec 02 16:01:14 CST 2019
     */
    public void setfName(String fName) {
        this.fName = fName == null ? null : fName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fruit.f_norm
     *
     * @return the value of fruit.f_norm
     *
     * @mbggenerated Mon Dec 02 16:01:14 CST 2019
     */
    public String getfNorm() {
        return fNorm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fruit.f_norm
     *
     * @param fNorm the value for fruit.f_norm
     *
     * @mbggenerated Mon Dec 02 16:01:14 CST 2019
     */
    public void setfNorm(String fNorm) {
        this.fNorm = fNorm == null ? null : fNorm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fruit.f_price
     *
     * @return the value of fruit.f_price
     *
     * @mbggenerated Mon Dec 02 16:01:14 CST 2019
     */
    public BigDecimal getfPrice() {
        return fPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fruit.f_price
     *
     * @param fPrice the value for fruit.f_price
     *
     * @mbggenerated Mon Dec 02 16:01:14 CST 2019
     */
    public void setfPrice(BigDecimal fPrice) {
        this.fPrice = fPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fruit.f_summary
     *
     * @return the value of fruit.f_summary
     *
     * @mbggenerated Mon Dec 02 16:01:14 CST 2019
     */
    public String getfSummary() {
        return fSummary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fruit.f_summary
     *
     * @param fSummary the value for fruit.f_summary
     *
     * @mbggenerated Mon Dec 02 16:01:14 CST 2019
     */
    public void setfSummary(String fSummary) {
        this.fSummary = fSummary == null ? null : fSummary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fruit.f_prompt
     *
     * @return the value of fruit.f_prompt
     *
     * @mbggenerated Mon Dec 02 16:01:14 CST 2019
     */
    public String getfPrompt() {
        return fPrompt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fruit.f_prompt
     *
     * @param fPrompt the value for fruit.f_prompt
     *
     * @mbggenerated Mon Dec 02 16:01:14 CST 2019
     */
    public void setfPrompt(String fPrompt) {
        this.fPrompt = fPrompt == null ? null : fPrompt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fruit.f_hot
     *
     * @return the value of fruit.f_hot
     *
     * @mbggenerated Mon Dec 02 16:01:14 CST 2019
     */
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fruit.f_imgcount
     *
     * @return the value of fruit.f_imgcount
     *
     * @mbggenerated Mon Dec 02 16:01:14 CST 2019
     */
    public Integer getfImgcount() {
        return fImgcount;
    }

    public Boolean getfHot() {
		return fHot;
	}

	public void setfHot(Boolean fHot) {
		this.fHot = fHot;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fruit.f_imgcount
     *
     * @param fImgcount the value for fruit.f_imgcount
     *
     * @mbggenerated Mon Dec 02 16:01:14 CST 2019
     */
    public void setfImgcount(Integer fImgcount) {
        this.fImgcount = fImgcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fruit.c_id
     *
     * @return the value of fruit.c_id
     *
     * @mbggenerated Mon Dec 02 16:01:14 CST 2019
     */
    public String getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fruit.c_id
     *
     * @param cId the value for fruit.c_id
     *
     * @mbggenerated Mon Dec 02 16:01:14 CST 2019
     */
    public void setcId(String cId) {
        this.cId = cId == null ? null : cId.trim();
    }
}