package com.jiaming.entity;

public class Star {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column star.sid
     *
     * @mbggenerated Mon Dec 02 16:01:14 CST 2019
     */
    private String sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column star.fid
     *
     * @mbggenerated Mon Dec 02 16:01:14 CST 2019
     */
    private Integer fid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column star.uid
     *
     * @mbggenerated Mon Dec 02 16:01:14 CST 2019
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column star.scount
     *
     * @mbggenerated Mon Dec 02 16:01:14 CST 2019
     */
    private Integer scount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column star.sid
     *
     * @return the value of star.sid
     *
     * @mbggenerated Mon Dec 02 16:01:14 CST 2019
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column star.sid
     *
     * @param sid the value for star.sid
     *
     * @mbggenerated Mon Dec 02 16:01:14 CST 2019
     */
    public void setSid(String sid) {
        this.sid = sid == null ? null : sid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column star.fid
     *
     * @return the value of star.fid
     *
     * @mbggenerated Mon Dec 02 16:01:14 CST 2019
     */
    public Integer getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column star.fid
     *
     * @param fid the value for star.fid
     *
     * @mbggenerated Mon Dec 02 16:01:14 CST 2019
     */
    public void setFid(Integer fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column star.uid
     *
     * @return the value of star.uid
     *
     * @mbggenerated Mon Dec 02 16:01:14 CST 2019
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column star.uid
     *
     * @param uid the value for star.uid
     *
     * @mbggenerated Mon Dec 02 16:01:14 CST 2019
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column star.scount
     *
     * @return the value of star.scount
     *
     * @mbggenerated Mon Dec 02 16:01:14 CST 2019
     */
    public Integer getScount() {
        return scount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column star.scount
     *
     * @param scount the value for star.scount
     *
     * @mbggenerated Mon Dec 02 16:01:14 CST 2019
     */
    public void setScount(Integer scount) {
        this.scount = scount;
    }
}